// drink customizer
export const SET_OPTIONS = 'SET_OPTIONS';
export const CHOOSE_BASE = 'CHOOSE_BASE';
export const ADD_ADD_ON = 'ADD_ADD_ON';
export const REMOVE_ADD_ON = 'REMOVE_ADD_ON';
export const CHOOSE_ICE_OR_SUGAR_LEVEL = 'CHOOSE_ICE_OR_SUGAR_LEVEL';
export const SET_DRINK_ORDER_DEFAULT = 'SET_DRINK_ORDER_DEFAULT';

// checkout
export const CHECKOUT_START = 'CHECKOUT_START';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';

// orders
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';