export const SET_OPTIONS = 'SET_OPTIONS';
export const CHOOSE_BASE = 'CHOOSE_BASE';
export const ADD_TOPPING = 'ADD_TOPPING';
export const REMOVE_TOPPING = 'REMOVE_TOPPING';
export const CHOOSE_ICE_OR_SUGAR_LEVEL = 'CHOOSE_ICE_OR_SUGAR_LEVEL';